# -*- coding: utf-8 -*-
"""主题 token 定义（深海驾驶舱 Deep Sea Cockpit 色板）。

- dark：深海声呐（深蓝底 + 声呐青 #00D4FF 主色 + 深空紫 #8B6BFF 次色）
- light：极地白鲸（浅色配套）

token 结构与 v2.22 完全一致（不增删键），只替换色值——
所有引用 token 的 UI（主窗口/对话框/面板）自动换肤，功能零改动。
"""

THEMES = {
    "light": {
        "name": "极地白鲸",
        "bg": "#e8f0f5",
        "page": "#f5f9fc",
        "panel": "#ffffff",
        "surface": "#e9f4f8",
        "border": "#d5e4ec",
        "chat_bg": "#ffffff",
        "text": "#14283f",
        "text_sec": "#5c7a96",
        "accent": "#00a3c8",
        "accent_hover": "#008fb0",
        "accent_text": "#ffffff",
        "bubble_user": "#0e9dbd",
        "bubble_user_text": "#ffffff",
        "bubble_assistant": "#eef3f8",
        "code_bg": "#eef4f7",
        "code_fg": "#1f8a70",
        "input_bg": "#ffffff",
        "input_fg": "#14283f",
        "selection": "#00a3c8",
        "thinking": "#57829c",
        "tool": "#8b6bff",
        "error": "#e5455c",
        "warning": "#e08f2e",
        "success": "#0fa878",
        "disabled": "#a9c0d4",
        "hover": "#e9f4f8",
        "note": "#57829c",
        "mention": "#00a3c8",
        "quote_bg": "#e3f5fb",
        "input_placeholder": "#8ba4bd",
    },
    "dark": {
        "name": "深海声呐",
        "bg": "#060a14",
        "page": "#0a101f",
        "panel": "#0e1729",
        "surface": "#14203a",
        "border": "#1f2c4d",
        "chat_bg": "#060a14",
        "text": "#e9f1ff",
        "text_sec": "#9db0d1",
        "accent": "#00d4ff",
        "accent_hover": "#33dfff",
        "accent_text": "#05121f",
        "bubble_user": "#0f5b7d",
        "bubble_user_text": "#e9f1ff",
        "bubble_assistant": "#0e1729",
        "code_bg": "#060a14",
        "code_fg": "#a8e6c8",
        "input_bg": "#0e1729",
        "input_fg": "#e9f1ff",
        "selection": "#00d4ff",
        "thinking": "#5e7196",
        "tool": "#8b6bff",
        "error": "#ff5d7a",
        "warning": "#ffb454",
        "success": "#2fe6a8",
        "disabled": "#41547a",
        "hover": "#14203a",
        "note": "#5e7196",
        "mention": "#00d4ff",
        "quote_bg": "#0d2440",
        "input_placeholder": "#41547a",
    },
}
